<a href="https://colab.research.google.com/github/ashishghanta/ml-learning-log_25/blob/main/1_intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,17)

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [8]:
a=np.array([1,5,8,13,41])

In [9]:
a

array([ 1,  5,  8, 13, 41])

In [10]:
a.size

5

In [11]:
a[4] = 17

In [12]:
a

array([ 1,  5,  8, 13, 17])

In [15]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.linspace(0,50,12)

array([ 0.        ,  4.54545455,  9.09090909, 13.63636364, 18.18181818,
       22.72727273, 27.27272727, 31.81818182, 36.36363636, 40.90909091,
       45.45454545, 50.        ])

In [28]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]

])

In [32]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
n[1][0]

np.int64(4)

In [34]:
n[1,0]

np.int64(4)

In [35]:
n[0,1]=33

In [36]:
n

array([[ 1, 33,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [38]:
n[2]=[4,4,4]

In [39]:
n

array([[ 1, 33,  3],
       [ 4,  5,  6],
       [ 4,  4,  4]])

In [41]:
n[1,:]

array([4, 5, 6])

In [42]:
n[:,2]

array([3, 6, 4])

In [72]:
np.random.seed(2)
100 * np.random.rand(4,3) #generates a random number between 0 to 1

array([[43.59949021,  2.59262318, 54.96624779],
       [43.53223926, 42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664, 29.96546737],
       [26.68272751, 62.11338328, 52.91420943]])

In [61]:
np.random.seed(2)
np.random.randn(4,3) #contains -ve values

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801]])

In [65]:
np.random.seed(2)
np.random.randint(low=0,high=50,size=(6,3))

array([[40, 15, 45],
       [ 8, 22, 43],
       [18, 11, 40],
       [ 7, 34, 49],
       [31, 11, 21],
       [47, 31, 26]])

In [66]:
a=np.arange(5)

In [67]:
a

array([0, 1, 2, 3, 4])

In [68]:
a*3

array([ 0,  3,  6,  9, 12])

In [69]:
b=a*2

In [70]:
b

array([0, 2, 4, 6, 8])

In [71]:
a>b

array([False, False, False, False, False])