<a href="https://colab.research.google.com/github/ashishghanta/ml-learning-log_25/blob/main/linear_alg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])

In [3]:
u

array([2, 4, 5, 6])

In [5]:
2 * u

array([ 4,  8, 10, 12])

In [6]:
v=np.array([1,0,0,2])

In [7]:
v

array([1, 0, 0, 2])

**Multiplication**

In [8]:
def vector_vector_multiplication(u,v):
  assert u.shape[0]==v.shape[0]
  n=u.shape[0]
  result = 0.0

  for i in range(n):
    result = result + u[i] * v[i]

  return result

In [9]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [12]:
u.dot(v)  # we can perform the above calculations using this inbuild function as well

np.int64(14)

In [14]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [15]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [20]:
U.shape

(3, 4)

In [33]:
def matrix_vector_multiplication(U,v):
  assert U.shape[1] == v.shape[0]
  num_rows = U.shape[0]

  result = np.zeros(num_rows)

  for i in range(num_rows):
    result[i]=vector_vector_multiplication(U[i],v)

  return result




In [34]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [35]:
U.dot(v)

array([14,  5,  5])

In [36]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [40]:
V.shape

(4, 3)

In [41]:
def matrix_matrix_multiplication(U,V):
  assert U.shape[1] == V.shape[0]

  num_rows = U.shape[0]
  num_cols = V.shape[1]

  result = np.zeros((num_rows, num_cols))

  for i in range(num_cols):
    vi = V[:,i]
    Uvi = matrix_vector_multiplication(U,vi)
    result[:, i] = Uvi

  return result



In [42]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

**Identity Matrix**

In [43]:
I = np.eye(3)

In [44]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [46]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [70]:
Vs = V[[0,1,2]]

In [71]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

**Inverse**

In [72]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [73]:
Vs_inv = np.linalg.inv(Vs)

In [74]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [75]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])