# HomeWork_1 -> Module 1: Introduction to Machine Learning_solutions

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.2'

In [3]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)

In [4]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [8]:
df.describe().round(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
count              9704.00        9222.00     8996.00         9704.00   
mean                199.71           3.96      149.66         3001.28   
std                  49.46           2.00       29.88          497.89   
min                  10.00           0.00       37.00          952.68   
25%                 170.00           3.00      130.00         2666.25   
50%                 200.00           4.00      149.00         2993.23   
75%                 230.00           5.00      170.00         3334.96   
max                 380.00          13.00      271.00         4739.08   

       acceleration  model_year  num_doors  fuel_efficiency_mpg  
count       8774.00     9704.00    9202.00              9704.00  
mean          15.02     2011.48      -0.01                14.99  
std            2.51        6.66       1.05                 2.56  
min            6.00     2000.00      -4.00                 6.20  
25%           13.30     2006.00      -1.00                13.27  
50%           15.00     2012.00       0.00                15.01  
75%           16.70     2017.00       1.00                16.71  
max           24.30     2023.00       4.00                25.97

In [11]:
df.shape

(9704, 11)

In [12]:
len(df). # count the records in the dataset

9704

In [13]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [14]:
df['fuel_type'].nunique() # To get the count of the unique fuel type = 2

2

In [15]:
df['fuel_type'].unique() # To get the list of unique fuel type = 2

array(['Gasoline', 'Diesel'], dtype=object)

In [19]:
df.isnull().sum() # There are 4 columns in the dataset having missing values

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [21]:
df.groupby('origin').fuel_efficiency_mpg.max().round(2) # Max fuel efficiency in Asia is 23.76

origin
Asia      23.76
Europe    25.97
USA       24.97
Name: fuel_efficiency_mpg, dtype: float64

In [26]:
before_hp = df['horsepower'].median() # Median value for the required column
before_hp

149.0

In [27]:
freq_hp = df['horsepower'].mode()[0] # Most frequent value for this given column
freq_hp

np.float64(152.0)

In [28]:
df['horsepower'] = df['horsepower'].fillna(freq_hp)

In [29]:
after_hp = df['horsepower'].median() #replaced most freq value in this column
after_hp

152.0

In [30]:
df_asia = df[df['origin']=='Asia']
df_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [31]:
df_selected = df_asia[['vehicle_weight', 'model_year']]

In [32]:
df_selected

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [33]:
df_top7 = df_selected.head(7)

In [34]:
df_top7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [35]:
X = df_top7.values

In [36]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [37]:
X.shape

(7, 2)

In [39]:
XTX = X.T @ X

In [40]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [41]:
XTX_inv = np.linalg.inv(XTX)

In [42]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [43]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [44]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [45]:
w = XTX_inv @ X.T @ y

In [46]:
w

array([0.01386421, 0.5049067 ])

In [47]:
result = w.sum()

In [51]:
print("Sum of all elements in w:", result.round(5))

Sum of all elements in w: 0.51877
